head: 
   favicon: "https://jekyllrb.com/favicon.ico" #  the favicon
   high_res_favicon: "/assets/images/jekyll-logo.png" #  the favicon using high quality format
   apple_touch_icon: "/assets/images/jekyll-logo.png" # the iOS Home button icon
   keywords: "blog jekyll mdui theme" #  the site keywords

uiux:
   android_chrome_color: "#eeeeee" #  the color of the Chrome address bar
   nprogress_color: "#fff" #  the color of the top loading progress bar
   meng: true # meng

background: 
   purecolor: "#2b7cd5" # the background color

img: 
   avatar: "/assets/images/jekyll-logo.png" # your avatar

card: 
   card_shadow: 1 # card shadow (0-24), 0 is not displayed
   card_hoverable: false # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: false
   googleplus: false
   weibo: false
   linkedin: false
   qq: false
   telegram: false
  
comment:
  used: "" # disqus,livere,gitment,valine
  # disqus config
  disqus_shortname: "" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: ''
  valine_app_key: ''
  valine_placeholder: "ヾﾉ≧∀≦)o来啊，快活啊!"

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

mathjax: true

google_analytics: ""  # google analytics code

google_site_verification: ""  # google search console verification code

lang: "zh-CN"  # lang

deploy: "" # if you used coding pages

custom_css: "customCss.css" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js